---
# -*- coding: utf-8 -*-

image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

before_script:
  - if [ -d ../lint-rules/.git ]; then
      cd ../lint-rules && git fetch -p && git pull;
    else
      git clone https://github.com/adfinis-sygroup/ansible-lint-rules ../lint-rules;
    fi
  - pip install --upgrade ansible ansible-lint
  - pip install --upgrade sphinx sphinx_rtd_theme
  - ansible-galaxy install -r requirements.yml

stages:
  - doc

build-sphinx:
  stage: doc
  script:
    - mkdir ansible-guide
    - make clean || true
    - make doc
    - mv doc/_build/html/* ansible-guide
  only:
    - master
  artifacts:
    paths:
      - ansible-guide/*

# vim: set ts=2 sw=2 :
