---
# -*- coding: utf-8 -*-

before_script:
  - pip install --upgrade ansible ansible-lint
  - ansible --version
  - ansible-lint --version

stages:
  - syntax
  - lint

syntax-check:
  stage: syntax
  script:
    - ansible-playbook site.yml --syntax-check

ansible-lint:
  stage: lint
  script:
    - ansible-lint -R -r .testenv/lint-rules/ site.yml
    - for f in *.yml; do
        grep -q tasks "$f" &&
        echo "File ${f} contains tasks" &&
        exit 1;
      done;
      exit 0

# vim: set ts=2 sw=2 tw=2 :
