---
# -*- coding: utf-8 -*-

image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

stages:
  - build-docs
  - publish-docs

build-docs:
  stage: build-docs
  script:
    - pip install --upgrade ansible
    - pip install --upgrade sphinx sphinx_rtd_theme
    - ansible --version
    - make requirements
    - cat requirements.yml
    - make install
    - git clone https://github.com/adfinis-sygroup/adsy-sphinx-template doc/sphinx-template
    - make doc
  artifacts:
    paths:
      - doc/_build/html/*

publish-docs:
  stage: publish-docs
  script:
    - mkdir ansible-guide
    - mv doc/_build/html/* ansible-guide
  only:
    - master
  artifacts:
    paths:
      - ansible-guide/*

# vim: set ts=2 sw=2 :
