---
# -*- coding: utf-8 -*-

before_script:
  - pip install --upgrade ansible ansible-lint
  - git submodule sync
  - git submodule update --init --recursive
  - ansible --version
  - ansible-lint --version

stages:
  - syntax
  - lint

syntax-check:
  stage: syntax
  script:
    - ansible-playbook site.yml --syntax-check

ansible-lint:
  stage: lint
  script:
    - ansible-lint site.yml

# vim: set ts=2 sw=2 tw=2 :
