---
# -*- coding: utf-8 -*-

image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

before_script:
  - pip install --upgrade ansible
  - pip install --upgrade sphinx sphinx_rtd_theme
  - ansible --version
  - mkdir ansible-guide
  - make requirements
  - cat requirements.yml
  - make install

stages:
  - build-docs
  - publish-docs

build-docs:
  stage: build-docs
  script:
    - make doc
  artifacts:
    paths:
      - doc/_build/html/*

publish-docs:
  stage: publish-docs
  script:
    - mv doc/_build/html/* ansible-guide
  only:
    - master
  artifacts:
    paths:
      - ansible-guide/*

# vim: set ts=2 sw=2 :
