---
# -*- coding: utf-8 -*-

before_script:
  - git submodule update --init

stages:
  - doc

build-sphinx:
  stage: doc
  script:
    - mkdir ansible-guide
    - make doc
    - mv doc/_build/html/* ansible-guide
  only:
    - master
  artifacts:
    paths:
      - ansible-guide/*

# vim: set ts=2 sw=2 tw=2 :
