---
# -*- coding: utf-8 -*-

before_script:
  - mkdir -p ~/.ssh
  - echo "$GITLAB_SSH_KEY" > ~/.ssh/id_rsa
  - echo "$GITLAB_SSH_KEY_PUB" > ~/.ssh/id_rsa.pub
  - chmod 600 ~/.ssh/id_rsa
  - export ANSIBLE_VAULT_PASSWORD_FILE=".testenv/vault-env"
  - git submodule update --init
  - pip install --upgrade ansible ansible-lint
  - ansible --version
  - ansible-lint --version

stages:
  - syntax
  - lint
  - doc

syntax-check:
  stage: syntax
  script:
    - ansible-playbook site.yml --syntax-check

ansible-lint:
  stage: lint
  script:
    - ansible-lint -R -r .testenv/lint-rules/ site.yml
    - for f in *.yml; do
        grep -q tasks "$f" &&
        echo "File ${f} contains tasks" &&
        exit 1;
      done;
      exit 0

build-sphinx:
  stage: doc
  script:
    - mkdir ansible-guide
    - make doc
    - mv doc/_build/html/* ansible-guide
  only:
    - master
  artifacts:
    paths:
      - ansible-guide/*

# vim: set ts=2 sw=2 tw=2 :
