# -*- coding: utf-8 -*-

before_script:
  - git submodule sync
  - git submodule update --init --recursive

stages:
  - syntax
  - lint

run-syntax:
  stage: syntax
  script:
    - ansible-playbook site.yml --syntax-check

run-lint:
  stage: lint
  script:
    - ansible-lint site.yml

# vim: set ts=2 sw=2 tw=2 :
