# -*- coding: utf-8 -*-

language: python
sudo: false
cache: pip
python:
  - "3.6"

install:
  - if [ -d ../lint-rules/.git ]; then
      cd ../lint-rules && git fetch -p && git pull;
    else
      git clone https://github.com/adfinis-sygroup/ansible-lint-rules ../lint-rules;
    fi
  - pip install --upgrade ansible ansible-lint
  - pip install --upgrade sphinx sphinx_rtd_theme

before_script:
  - export ANSIBLE_VAULT_PASSWORD_FILE=".testenv/vault-env"
  - ERRORS=0
  - git submodule update --init
  - ansible --version
  - ansible-lint --version
  - mkdir ansible-guide
  - ansible-galaxy install -r requirements.yml

script:
  - ansible-playbook site.yml --syntax-check || let ERRORS+=1
  - ansible-lint -R -r ../lint-rules site.yml || let ERRORS+=1
  - for f in *.yml; do
      grep -q tasks "$f" &&
      echo "File ${f} contains tasks" &&
      let ERRORS+=1;
    done
  - make doc
  - mv doc/_build/html/* ansible-guide
  - exit $ERRORS

# vim: set ts=2 sw=2 tw=2 :
