# -*- coding: utf-8 -*-

language: python
sudo: false
cache: pip
python:
  - "3.6"

install:
  - pip install --upgrade ansible
  - pip install --upgrade sphinx sphinx_rtd_theme

before_script:
  - ansible --version
  - mkdir ansible-guide
  - make requirements
  - make install

script:
  - make doc
  - mv doc/_build/html/* ansible-guide

# vim: set ts=2 sw=2 tw=2 :
