---
# -*- coding: utf-8 -*-

- src: adfinis-sygroup.ansible
  version: master
- src: adfinis-sygroup.console
  version: master
- src: adfinis-sygroup.docker
  version: master
- src: adfinis-sygroup.grub
  version: master
- src: adfinis-sygroup.hostname
  version: master
- src: adfinis-sygroup.hwraid
  version: master
- src: adfinis-sygroup.hw_vm_tools
  version: master
- src: adfinis-sygroup.ipmi
  version: master
- src: adfinis-sygroup.iptables
  version: master
- src: adfinis-sygroup.mariadb
  version: master
- src: adfinis-sygroup.motd
  version: master
- src: adfinis-sygroup.network
  version: master
- src: adfinis-sygroup.nginx
  version: master
- src: adfinis-sygroup.nodejs
  version: master
- src: adfinis-sygroup.ntp
  version: master
- src: adfinis-sygroup.pkg_mirror
  version: master
- src: adfinis-sygroup.pki
  version: master
- src: adfinis-sygroup.postfix
  version: master
- src: adfinis-sygroup.rpcbind
  version: master
- src: adfinis-sygroup.rsyslog
  version: master
- src: adfinis-sygroup.snmp
  version: master
- src: adfinis-sygroup.ssh
  version: master
- src: adfinis-sygroup.telegraf
  version: master
- src: adfinis-sygroup.upgrade
  version: master
- src: adfinis-sygroup.users
  version: master

# vim: set ts=2 sw=2 :
