---

- hosts: all
  gather_facts: True
  vars:
    - dist_upgrade: True
  roles:
    - upgrade
    - test_env

- hosts: all
  gather_facts: False
  roles:
    - ansible
    - console
    - ntp
    - ssh
    - pki
    - snmp
    - nginx
    - mariadb
    - telegraf

- hosts: Debian_7
  gather_facts: False
  roles: []

- hosts: Debian_8
  gather_facts: False
  roles:
    - nodejs

- hosts: CentOS_6
  gather_facts: False
  roles: []

- hosts: CentOS_7
  gather_facts: False
  roles:
    - nodejs

- hosts: Ubuntu_14
  gather_facts: False
  roles: []

- hosts: Ubuntu_16
  gather_facts: False
  roles:
    - nodejs
