---

- hosts: all
  gather_facts: True
  vars:
    - dist_upgrade: True
  roles:
    - pkg_mirror
    - upgrade
    - ansible
    - hostname
    - test_env

- hosts: all
  gather_facts: False
  roles:
    - console
    - iptables
    - mariadb
    - motd
    - network
    - nginx
    - ntp
    - pki
    - postfix
    - rpcbind
    - rsyslog
    - snmp
    - ssh
    - users

- hosts: Debian_7
  gather_facts: False
  roles:
    - grub
    - telegraf

- hosts: Debian_8
  gather_facts: False
  roles:
    - grub
    - nodejs
    - telegraf

- hosts: Debian_9
  gather_facts: False
  roles:
    - grub

- hosts: CentOS_6
  gather_facts: False
  roles:
    - telegraf

- hosts: CentOS_7
  gather_facts: False
  roles:
    - grub
    - nodejs
    - telegraf

- hosts: Ubuntu_14
  gather_facts: False
  roles:
    - grub
    - telegraf

- hosts: Ubuntu_16
  gather_facts: False
  roles:
    - grub
    - nodejs
    - telegraf
