---

# Playbook site.
# Used to run all roles against the test infrastructure.


- hosts: all
  gather_facts: True
  vars:
    - dist_upgrade: True
  roles:
    - adfinis-sygroup.pkg_mirror
    - adfinis-sygroup.upgrade
    - adfinis-sygroup.ansible
    - adfinis-sygroup.hostname
    - test_env

- hosts: all
  gather_facts: False
  roles:
    - adfinis-sygroup.console
    - adfinis-sygroup.hwraid
    - adfinis-sygroup.hw_vm_tools
    - adfinis-sygroup.ipmi
    - adfinis-sygroup.iptables
    - adfinis-sygroup.mariadb
    - adfinis-sygroup.motd
    - adfinis-sygroup.network
    - adfinis-sygroup.nginx
    - adfinis-sygroup.ntp
    - adfinis-sygroup.pki
    - adfinis-sygroup.postfix
    - adfinis-sygroup.rpcbind
    - adfinis-sygroup.rsyslog
    - adfinis-sygroup.snmp
    - adfinis-sygroup.ssh
    - adfinis-sygroup.telegraf
    - adfinis-sygroup.users

- hosts: Debian_7
  gather_facts: False
  roles:
    - adfinis-sygroup.docker
    - adfinis-sygroup.grub

- hosts: Debian_8
  gather_facts: False
  roles:
    - adfinis-sygroup.docker
    - adfinis-sygroup.grub
    - adfinis-sygroup.nodejs

- hosts: Debian_9
  gather_facts: False
  roles:
    - adfinis-sygroup.docker
    - adfinis-sygroup.grub
    - adfinis-sygroup.nodejs

- hosts: CentOS_6
  gather_facts: False
  roles: []

- hosts: CentOS_7
  gather_facts: False
  roles:
    - adfinis-sygroup.docker
    - adfinis-sygroup.grub
    - adfinis-sygroup.nodejs

- hosts: Ubuntu_14
  gather_facts: False
  roles:
    - adfinis-sygroup.docker
    - adfinis-sygroup.grub

- hosts: Ubuntu_16
  gather_facts: False
  roles:
    - adfinis-sygroup.docker
    - adfinis-sygroup.grub
    - adfinis-sygroup.nodejs
