---

mariadb_databases:
  - name: ghost
  - name: marketing

mariadb_users:
  - name: ghost
    password: '{{ mariadb_user_ghost_password }}'
    priv: 'ghost.*:ALL'
  - name: john
    host: localhost
    password: '{{ mariadb_user_john_password }}'
    priv: 'database1.*:ALL'
  - name: hans
    host: www.example.com
    password: '{{ mariadb_user_hans_password }}'
    priv: '*.*:ALL,GRANT'
  - name: replication
    password: '{{ mariadb_user_replication_password }}'
    priv: '*.*:REPLICATION CLIENT'
  - name: web
    password: '{{ mariadb_user_web_password }}'
    priv: 'ghost.*:INSERT,UPDATE/marketing.*:SELECT'
