# network configuration options

network_resolv_nameservers:
  - 8.8.8.8
  - 8.8.4.4

network_interfaces:
  - device: eth0
    tmpl: ethernet
    ipv4:
      type: dhcp
    ipv6:
      type: manual
  - device: enp0s3
    tmpl: ethernet
    ipv4:
      type: dhcp
    ipv6:
      type: manual
  - device: foo
    tmpl: ethernet
    ipv4:
      type: manual
    ipv6:
      type: manual
