---

nginx_vhosts:
  # documentroot and php
  - name: www.example.com
    default: true
    type: standard
    acme: True
    ssl_dhparam: '{{ pki_dhparam_file }}'
    ssl_crt: '{{ pki_snakeoil.cert }}'
    ssl_key: '{{ pki_snakeoil.pkey }}'
    hsts: true
    ssl_hsts_age: 15768000
    ssl_stapling: true
    document_root: /var/www/www.example.com
    index: index.html
    php_enabled: true
  # this example shows how to create a reverse proxy with an upstream server
  - name: proxy.example.com
    type: proxy
    status:
      page: /status
      allows:
        - 127.0.0.1
    ssl_dhparam: '{{ pki_dhparam_file }}'
    ssl_crt: '{{ pki_snakeoil.cert }}'
    ssl_key: '{{ pki_snakeoil.pkey }}'
    proxy:
      - src: /
        dest: http://localhost:8080/
  # this example shows how to configure a website with cgi-bin
  - name: icinga.example.com
    type: standard
    ssl_dhparam: '{{ pki_dhparam_file }}'
    ssl_crt: '{{ pki_snakeoil.cert }}'
    ssl_key: '{{ pki_snakeoil.pkey }}'
    document_root: /usr/share/icinga/htdocs
    alias:
      - src: /icinga
        dest: /usr/share/icinga/htdocs
      - src: /stylesheets
        dest: /etc/icinga/stylesheets
      - src: /icinga/stylesheets
        dest: /etc/icinga/stylesheets
    cgi_bin:
      - location: /cgi-bin/icinga
        root: /usr/lib/cgi-bin/icinga
        document_root: /usr/lib
