---

# password: password
users_root_password: '$6$99CJ1xdgqGrO$I.HzKgbtgx/5Zgx1QxuPrmJvNIpBMUjg83GNNkk7OV5NQo6437aVZf7FaV9vPpvY79ekaEesDT.42mrOTN/NJ1'
users_root_password_update: always

users_user:
  - name: JohnDoe
    uid: 5000
    gid: 5000
    group: users
    groups: []
    comment: "John Doe"
    # password: password
    password: '$6$6hSIphBjuA$Z160GKoK268qjgRhWo6KjgsuIiEyQmLzGq6uApGm.aHrlvnNXFx/KyrnWIJTVXeGR3Bo9ZB/.qsex8PZHlBSy0'
    update_password: always
    system: True
    shell: /bin/bash
    home: /home/johndoe
    createhome: True
    expires: 1800000000
    remove: False
    state: present
    sshkeys: []

users_ssh_keys:
  - user: root
    key: '{{ lookup("file", "ssh/root.pub") }}'
    key_options: 'from="192.0.2.1"'
    exclusive: true
